### ISSUE TITLE
WP 6.1.1 - Color Picker modal falls off screen on MacOS ALL browsers 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generatepress#476]
### Description
Modal is inaccessible:

<img width="308" alt="Screenshot 2022-11-16 at 15 49 07" src="https://user-images.githubusercontent.com/30641942/202228568-e72db239-0dbf-4863-92dc-dc241802a77e.png">

**Comment by tomusborne** [comment]
This is only an issue when using the latest Gutenberg plugin.

It will be fixed in GP 3.3.

**Comment by codysmith44** [comment]
@tomusborne This is happening for me on a default install of WP 6.1.1 - no other plugins, standard WP (not using the Gutenberg plugin.)

![screenshot_2022-11-16_000390](https://user-images.githubusercontent.com/3072786/202307535-dc30d1d2-4823-4e8e-88db-94598e2e98a9.jpg)

**Comment by tomusborne** [comment]
@codysmith44 Confirmed - thanks for the nudge! Any chance you can see if it's fixed in this version?: https://github.com/tomusborne/generatepress/suites/9349782523/artifacts/439895324

Thanks!

**Comment by codysmith44** [comment]
@tomusborne Still having the same issue using that version. I can send you login credentials if you'd like (just a temporary site I spun up on InstaWP). Not sure where to send those credentials, though. 
![screenshot_2022-11-16_000391@2x](https://user-images.githubusercontent.com/3072786/202321400-33f0da7b-bd29-43ef-ba4f-7c44f2e7c8f6.jpg)

**Comment by tomusborne** [comment]
@codysmith44 That would be awesome - support@generatepress.com would be the best place for that, just be sure to mention this issue.

Thank you!

**Comment by codysmith44** [comment]
@tomusborne oops, yep that did the trick. Sorry! Thanks for the quick responses btw.

**Comment by tomusborne** [comment]
Awesome, glad it's working. Thanks for testing, really appreciate it!
